spring:
  datasource:
    #    driver-class-name: oracle.jdbc.driver.OracleDriver
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  liquibase:
    enabled: true
#    enabled: false
    change-log: liquibase/liquibase-outputChangeLog.xml
    drop-first: true
#server:
#  port: 9090