spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@//172.19.0.1:1521/ORCLPDB1
    username: localdev
    password: localdev
  liquibase:
    enabled: true
#    enabled: false
    change-log: liquibase/liquibase-outputChangeLog.xml
    drop-first: true
  jpa:
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: update
              create-target: update.sql
server:
  port: 9090


logging:
  level:
    ru:
      vood: info
#springdoc:
#  api-docs:
#    path:/api-docs


