spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@//172.26.0.1:1521/ORCLPDB1
    username: localdev
    password: localdev
  liquibase:
    enabled: true
    change-log: liquibase/liquibase-outputChangeLog.xml
server:
  port: 9090