spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@//172.19.0.1:1521/ORCLPDB1
    username: localdev
    password: localdev
server:
  port: 9090


logging:
  level:
    ru:
      vood: info

springdoc:
  show-actuator: true
  swagger-ui:
    config-url: qwerty
#springdoc:
#  api-docs:
#    path: /v3/api-docs